### ISSUE TITLE
Adapt to new wildfly-cli fat client shaded model

### ISSUE THREAD

**Issue by jfdenise** [wildfly/wildfly-plugin-tools#86]
Issue: https://issues.redhat.com/browse/WFMP-279
WildFly is producing a model of the shaded wildfly-cli:client fat jar. This shaded model should be used to construct CLI classloader.

**Comment by jamezp** [comment]
Is there a JIRA for the task that added this?

**Comment by jfdenise** [comment]
@jamezp , I logged: https://issues.redhat.com/browse/WFMP-279

**Comment by jamezp** [comment]
@jfdenise Sorry, I meant a WFLY or WFCORE JIRA. From what it looks like `org.wildfly.core.wildfly-cli.shaded` package which I assume is part of either the WildFly or WildFly Core feature packs. There is no JavaDoc to `GalleonFeaturePackRuntime.GalleonPackageRuntime()`, but my assumption on reading the code is it will simply return `null` if not found. Is that correct?

I guess what I didn't know is what `org.wildfly.core.wildfly-cli.shaded` is, but I'm assuming it must be a package in the feature pack.

**Comment by jfdenise** [comment]
@jamezp , I see, The JIRA that introduced this package is: https://issues.redhat.com/browse/WFCORE-7019

**Comment by jamezp** [comment]
Perfect, thank you! I'll give it a test.
